[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  VITE_API_URL = "https://your-api-url.com"

[dev]
  command = "npm run dev"
  port = 8080 