[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "node scripts/netlify-build.cjs"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  # Use a mock API URL for now - this will be replaced with the real API URL later
  VITE_API_URL = ""

[dev]
  command = "npm run dev"
  port = 8080 